from tkinter import *
from tkinter import messagebox
import RPi.GPIO as GPIO 
top=Tk()
GPIO.setmode(GPIO.BCM)
GPIO.setup(18,GPIO.OUT)
GPIO.setup(17,GPIO.OUT)
GPIO.setup(15,GPIO.OUT)
pw1=GPIO.PWM(15,500)
pw2=GPIO.PWM(17,500)
pw1.start(100)
pw2.start(100)
def n2():
    def s1():
        l8.config(text="LED IS On")
        GPIO.output(18,True)
    def s2():
        l8.config(text="LED IS OFF")
        GPIO.output(18,False)
    def s3():
        l8.config(text="Motor IS ON")
    def s4():
        l8.config(text="MOTOR IS OFF")
    def s5(value):
        s2.set(s1.get())
        l8.config(text=s1.get())
        
        duty1=int(value)
        pw1.ChangeDutyCycle(duty1)
            
    def s6(value1):
        s4.set(s3.get())
        l8.config(text=s3.get())
        duty2=int(value1)
        pw2.ChangeDutyCycle(duty2)
        
    l1=Label(top,text="led on switch").place(x=100,y=200)
    b1=Button(top,text="ON",bg="green",command=s1).place(x=100,y=250)
    l2=Label(top,text="Led off swicth").place(x=100,y=350)
    b2=Button(top,text="OFF",bg="red",command=s2).place(x=100,y=400)
    l1=Label(top,text="motor on swicth").place(x=100,y=450)
    b1=Button(top,text="ON",bg="green",command=s3).place(x=100,y=500)
    l2=Label(top,text="motor off swicth").place(x=100,y=550)
    b2=Button(top,text="OFF",bg="red",command=s4).place(x=100,y=600)
    f2=Frame(top)
    f2.pack(side=TOP)
    l4=Label(top,text="Brightness controll of Led").place(x=400,y=10)
    s1=Scale(top,from_=0,to=100,length="250",orient="horizontal",command=s5)
    s1.pack(side=TOP)
    l5=Label(top,text="Brightness Amount in %").place(x=400,y=40)
    s2=Scale(top,from_=0,to=100,length="250",orient="horizontal",bg="yellow",fg="red")
    s2.pack(side=TOP)
    l6=Label(top,text="Angle Of Servo MOTOR").place(x=400,y=120)
    s3=Scale(top,from_=0,to=180,length="250",orient="horizontal",command=s6)
    s3.pack(side=TOP)
    l7=Label(top,text="Angle rotated").place(x=400,y=150)
    s4=Scale(top,from_=0,to=180,length="250",orient="horizontal",bg="red",fg="blue")
    s4.pack(side=TOP)
    l9=Label(top,text="OUTPUT WINDOW").place(x=900,y=200)
    l8=Label(top,bg="white",width="90",height="30")
    l8.pack(side=RIGHT) 

menubar=Menu(top)
file=Menu(menubar,tearoff=0)
file.add_command(label="open interface",command=n2)
file.add_command(label="Save")
file.add_command(label="Copy")
menubar.add_cascade(label="File",menu=file)
edit=Menu(menubar,tearoff=0)
edit.add_command(label="Undo")
edit.add_command(label="Cut")
edit.add_command(label="Document")
menubar.add_cascade(label="EDIT",menu=edit)
tools=Menu(menubar,tearoff=0)
tools.add_command(label="Sensor")
tools.add_command(label="LED")
tools.add_command(label="MOTOR")
menubar.add_cascade(label="TOOLS",menu=tools)
top.config(menu=menubar)
top.mainloop()